version: '3.7'

services:
    db:
        image: postgres:13
        restart: ${RESTART:-no}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123change}
        volumes:
            - ./env/db:/var/lib/postgresql/data
        networks:
            - app-newtwork

    app:
        build: todolist
        depends_on:
            - db
        volumes:
            - ./:/app
        working_dir: /app/todolist
        ports:
            - "8000:8000"
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        networks:
            - app-newtwork

networks:
    app-newtwork:
