version: '3.7'

services:
    db:
        image: postgres:13
        restart: ${RESTART:-no}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123change}
        volumes: 
            - ./env/db:/var/lib/postgresql/data
        networks: 
            - app-newtwork

    app:
        build: todolist
        restart: ${RESTART:-no}
        depends_on: 
            - db
        links: 
            - db:db_postgres
        volumes: 
            - ./:/app
        working_dir: /app/todolist
        ports: 
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        networks:
            - app-newtwork
    
        command: ${RUNSERVER:-/bin/bash} 

networks:
    app-newtwork: