# Generated by Django 3.2.9 on 2021-11-12 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 12, 16, 35, 46, 860329))),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 12, 16, 35, 46, 860369))),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('START', 'Start'), ('FINISHED', 'Finished')], default='START', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 12, 16, 35, 46, 861268))),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 12, 16, 35, 46, 861300))),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TO DO', 'To-do'), ('IN PROGRESS', 'Progress'), ('FINISHED', 'Finished')], default='TO DO', max_length=11)),
                ('set_task_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.settaskmodel')),
            ],
        ),
    ]
