# Generated by Django 3.2.9 on 2021-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211112_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settaskmodel',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='settaskmodel',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
