# Generated by Django 3.2.9 on 2021-11-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211112_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetTaskModel',
            new_name='ListTaskModel',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='set_task_model',
            new_name='list_task_model',
        ),
    ]
