# Generated by Django 3.2.9 on 2021-11-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211119_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listtaskmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='list_task_id',
            new_name='list_task',
        ),
    ]
