# Generated by Django 3.2.9 on 2021-11-29 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_taskmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TO DO', 'To-do'), ('IN PROGRESS', 'Progress'), ('FINISHED', 'Finished')], default='TO DO', max_length=11)),
            ],
        ),
        migrations.RenameModel(
            old_name='ListTaskModel',
            new_name='ListOfTask',
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
        migrations.AddField(
            model_name='task',
            name='list_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listoftask'),
        ),
    ]
