# Generated by Django 3.2.9 on 2021-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211129_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='list_task',
        ),
        migrations.AddField(
            model_name='listoftask',
            name='tasks',
            field=models.ManyToManyField(to='app.Task'),
        ),
    ]
